### PR TITLE
Totally re-factored JS, cleaned up CSS & PHP

### PR DESCRIPTION
**Pull request by ghost**
All coded in lovely jQuery (which is on MediaWiki by default).

Same functionality, but added new features, most notably:
- Faster and cleaner handling (speed improvements)
- Hash urling (you can directly link to a tab via hash link)

### CODE REVIEW

**Comment by ghost** [comment]
Should work with issue #1 Alexia mentioned, but writing a custom fn for it (which I have done).

**Comment by Telshin** [comment]
Looking over this today and testing against some of the wikis in the farm.

**Comment by ghost** [comment]
Lack of reply as currently on mobile.

If this doesn't work, get back to me and I can take a look, it's un-tested, but it was a generic 5 minute re-write. Will probably make it a lot more cleaner (possibly hook into jQuery's UI system that's inbuilt to MediaWiki now)

**Comment by Telshin** [comment]
Looks like everything works on the test wikis. Merging into the default Tabber.

**Comment by ghost** [comment]
Wahey, something I did works xD

**Pull request merged**
